licenses(["notice"]) # Apache 2.0
package(default_visibility = ["//visibility:public"])
cc_library(
 name = "desktop_tflite_calculators",
 deps = [
 "//mediapipe/calculators/util:simple_flow_calculator",
 ],
 )