licenses(["notice"]) # Apache 2.0

package(default_visibility = ["//mediapipe/examples:__subpackages__"])
cc_binary(
name = "face_keypoint_cpu",
deps = [
"//mediapipe/examples/desktop:demo_run_graph_main",
"//mediapipe/graphs/face_keypoint:desktop_tflite_calculators",
],
)